add_newline = false 
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"
right_format = "$all"

[profiles]
transient = """$character"""

[character]
success_symbol = "[❯](fg:#7aa2f7)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = "bold fg:#7aa2f7"
repo_root_style = "bold fg:#7aa2f7"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "green"

[git_status]
format = "[$stashed_first$all_status$ahead_behind]($style)" 
style = "bold blue" 
ahead      = "[ ⇡${count}](bold cyan)"
behind     = "[ ⇣${count}](bold cyan)"
conflicted = "[ ](bold yellow)"
deleted    = ""
diverged   = "[ ⇕ ⇡${ahead_count}⇣${behind_count}](bold red)"
modified   = "[ !${count}](bold #e0af68)"
renamed    = ""
staged     = ""
stashed    = "[ *${count}](bold #9ece6a)"
untracked  = "[ ?${count}](bold #bb9af7)"
up_to_date = "[ ](bold green) "

[package]
disabled = true

[python]
format = '[$symbol$version ]($style)'

[rust]
format = '[$symbol$version ]($style)'

[golang]
format = '[$symbol$version ]($style)'

[nodejs]
format = '[$symbol$version ]($style)'

[zig]
format = '[$symbol$version ]($style)'
